name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        id: review
        with:
          fail-on-severity: critical
          deny-licenses: LGPL-2.0, BSD-2-Clause
          comment-summary-in-pr: always
          license-check: true
      - name: 'Report'
        if: ${{ failure() && steps.review.conclusion == 'failure' }}
        shell: bash
        env: 
          COMMENT: ${{ steps.review.outputs.comment-content }}
        run: | 
          echo "$COMMENT"
      - name: 'List vulnerable dependencies'
        if: ${{ failure() && steps.review.conclusion == 'failure' }}
        shell: bash
        env: 
          VULNERABLE_CHANGES: ${{ steps.review.outputs.vulnerable-changes }}
        run: | 
          echo "$VULNERABLE_CHANGES" | jq '.[].package_url'